class NameMapper {
  static final Map<int, String> _nameMap = {
    1: 'Chiranjeevi',
    2: 'Nagarjuna',
    3: 'Venkatesh',
    4: 'Balakrishna',
    5: 'Pawan Kalyan',
    6: 'Mahesh Babu',
    7: 'Allu Arjun',
    8: 'Ram Charan',
    9: 'Prabhas',
    10: 'N.T.R Jr.',
    11: 'Nani',
    12: 'V.Deverakonda',
    13: 'Ravi Teja',
    14: 'Sharwanand',
    15: 'Naga Chaitanya',
    16: 'Nikhil',
    17: 'Gopichand',
    18: 'Manchu Vishnu',
    19: 'Sundeep Kishan',
    20: 'Varun Tej',
    21: 'Akhil Akkineni',
    22: 'B. Sreenivas',
    23: 'Adivi Sesh',
    24: 'Srinivas Avasarala',
    25: 'Krishna',
    26: 'A.N.R',
    27: 'Sobhan Babu',
    28: 'Krishnam Raju',
    29: 'Mohan Babu',
    30: 'Srikanth',
    31: 'Tarun',
    32: 'Sumanth',
    33: 'Siddharth',
    34: 'Vishnu Manchu',
    35: 'Rana',
    36: 'Jagapati Babu',
    37: 'Prakash Raj',
    38: 'Sunil',
    39: 'Ali',
    40: 'Brahmanandam',
    41: 'Venu',
    42: 'Rajendra Prasad',
    43: 'Harish Shankar',
    44: 'Sai Dharam Tej',
    45: 'Nithiin',
    46: 'Samantha',
    47: 'Kajal',
    48: 'Anushka',
    49: 'Tamannaah',
    50: 'Rakul',
    51: 'Shriya',
    52: 'Trisha',
    53: 'Nayanthara',
    54: 'Ileana',
    55: 'Genelia',
    56: 'Asin',
    57: 'Hansika',
    58: 'Taapsee',
    59: 'Regina',
    60: 'Richa',
    61: 'Lakshmi ',
    62: 'Catherine ',
    63: 'Rashi',
    64: 'Pooja',
    65: 'Rashmika',
    66: 'Sai',
    67: 'Anupama',
    68: 'Nabha Natesh',
    69: 'Priyadarshini',
    70: 'Hebah Patel',
    71: 'Krithi Shetty',
    72: 'Priya',
    73: 'Savitri',
    74: 'Vanisri',
    75: 'Jayasudha',
    76: 'Vijayashanti',
    77: 'Radhika',
    78: 'Suhasini',
    79: 'Soundarya',
    80: 'Ramya Krishna',
    81: 'Raadhika',
    82: 'Meena',
    83: 'Sridevi',
    84: 'Revathi',
    85: 'Gautami',
    86: 'Bhanumati',
    87: 'Jamuna',
    88: 'Jayaprada',
    89: 'Roopa',
    90: 'Shobana',
  };

  static String getName(int number) {
    return _nameMap[number] ?? number.toString();
  }

  static String getDisplayValue(int number, bool useNames) {
    return useNames ? getName(number) : number.toString();
  }
}
